### ISSUE TITLE
Ruleset: APT_ShadowHammer false positive

### ISSUE THREAD

**Issue by tkloos** [advanced-threat-research/Yara-Rules#10]
The last several 64-bit Firefox install files are being flagged by this on VirusTotal.
Firefox Setup 81.0.exe
Firefox Setup 81.0.2.exe
and now Firefox Setup 82.0.exe

Have not checked 32-bit release files.  All are available here:  https://archive.mozilla.org/pub/firefox/releases/

**Comment by fr0gger** [comment]
Rule removed thanks.
