### ISSUE TITLE
RANSOM_Darkside.yar vs RANSOM_darkside.yar

### ISSUE THREAD

**Issue by jakubkroustek** [advanced-threat-research/Yara-Rules#17]
Hello,

I just spotted that you have two rulesets for the same family `RANSOM_Darkside.yar` and `RANSOM_darkside.yar`. However, this file naming causes issues on systems with case-insensitive file systems, such as Windows. As a results, your repository cannot be properly cloned, etc. Consider unifying these two in one ruleset. 

Thank you

**Comment by ThisIsLibra** [comment]
Thank you for opening this issue, even though my reply is rather late. I just merged the pull request by @mavjs. Cheers!
