### ISSUE TITLE
Trellix (FireEye) False Positive on VirusTotal.com

### ISSUE THREAD

**Issue by eracs-rina** [advanced-threat-research/Yara-Rules#19]
I am a developer in the RINA Tech UK software team who authored a file which has been reported as "Gen:Variant.Lazy.398487" on virustotal.com by the Trellix (FireEye) engine, when 82% of anti-virus engines did not detect any issues. I believe the Trellix (FireEye) results to be a false positive. 

I have uploaded it to a cloud storage service provided by my company:
https://depot.rina.org/access/kWvx5atetqkys4qoS5DWfMY2ch5n
[The password for the uploaded file is “infected” (without the double quotes)]

If you'd like any further information, please let me know.

Many thanks,
Clive

**Comment by wikijm** [comment]
Hi @eracs-rina,

I'm curious about your case.
In you opinion, which Yara file from that repository is triggering an alert for your file?

**Comment by ThisIsLibra** [comment]
Hello,

Thank you for reaching out. Please submit the alleged false positive per the [Trellix documentation](https://kcm.trellix.com/corporate/index?page=content&id=KB85567). This repository is for Yara rules, and it sounds like your issue is different from this repository's purpose.

Cheers,
Max
