### ISSUE TITLE
Broken rule: Tortoiseshell SYSkit

### ISSUE THREAD

**Issue by deadbits** [advanced-threat-research/Yara-Rules#2]
On line 7 in the meta section, the field is using a colon as a separator instead of the required equal sign. Link to the line is below

https://github.com/advanced-threat-research/Yara-Rules/blob/6591646e8f5f00939a13c2155dbfa56e3d1aaaf0/APT/APT_Tortoiseshell_Syskit#L7

**Comment by seifreed** [comment]
Thanks!

I made a PR and now the rule is fixed

https://github.com/advanced-threat-research/Yara-Rules/commit/e51c71ca64e8ee89fc0c2ed38361e401243ab800
